### ISSUE TITLE
Please publish 1.1

### ISSUE THREAD

**Issue by sethladd** [dart-lang/resource#12]
To fix the "two resource libraries" issue :)

Thanks!

**Comment by hermanbergwerf** [comment]
Somehow I cannot `pub get` this package:
```
Resolving dependencies... 
Package resource has no versions that match >=1.1.0 <2.0.0 derived from:
- <my_package> depends on version ^1.1.0
```
Could that be related?

**Comment by sethladd** [comment]
1.1 seems to be released. https://pub.dartlang.org/packages/resource

pub also tries to match your SDK version, so maybe that's why it can't find 1.1.0 for you. What version are you using? https://github.com/dart-lang/resource/blob/master/pubspec.yaml

Going to close because the original intent of the issue is fixed.

**Comment by hermanbergwerf** [comment]
Ok, I have `>=1.8.0 <2.0.0`. I still have Dart 1.13.1 on my local machine. I guess Resource is still not deprecated there (which is probably the reason for this package to be for Dart 1.14<). I'll update Dart on my machine, thanks.
